language: python
python:
  - "3.6" 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - export APP_SETTINGS="config.DevelopmentConfig"
  - export DATABASE_URL="postgresql://postgres:postgres@localhost/DBNAME"
  - rm -r migrations
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
# command to run tests
script:
  - pytest
