"""empty message

Revision ID: 3b54285486e0
Revises: 8019278424a4
Create Date: 2019-02-13 16:12:48.249794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b54285486e0'
down_revision = '8019278424a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('initial_investment', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'initial_investment')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
